//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiologyDepartment.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dwbtechnologies.ddns.net:390")]
        public string MyActiveDirectory {
            get {
                return ((string)(this["MyActiveDirectory"]));
            }
            set {
                this["MyActiveDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=dwbtechnologies.ddns.net")]
        public string MyPostgress {
            get {
                return ((string)(this["MyPostgress"]));
            }
            set {
                this["MyPostgress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dwbtechnologies.ddns.net:8787/rstudio")]
        public string MyRStudio {
            get {
                return ((string)(this["MyRStudio"]));
            }
            set {
                this["MyRStudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost:389")]
        public string MyActiveDirectoryTest {
            get {
                return ((string)(this["MyActiveDirectoryTest"]));
            }
            set {
                this["MyActiveDirectoryTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string MyPostgresTest {
            get {
                return ((string)(this["MyPostgresTest"]));
            }
            set {
                this["MyPostgresTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.10:8787/rstudio")]
        public string MyRstudioTest {
            get {
                return ((string)(this["MyRstudioTest"]));
            }
            set {
                this["MyRstudioTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8888/showLogin.cc")]
        public string PasswordTest {
            get {
                return ((string)(this["PasswordTest"]));
            }
            set {
                this["PasswordTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dwbtechnologies.ddns.net:8888/showLogin.cc")]
        public string PasswordActive {
            get {
                return ((string)(this["PasswordActive"]));
            }
            set {
                this["PasswordActive"] = value;
            }
        }
    }
}
